/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package herenciap;

import java.util.Map;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mfarias
 */
public class Pantalla extends javax.swing.JFrame {
    
    private String[] marcasAuto = {"Toyota","Hyunday" ,"Susuki", "Ford", "Chevrolet","Honda"};
    private String[] marcasMoto = {"Yamaha", "Suzuki", "Honda","KTM","BMW","Kawasaki"};
    private String[] marcasCamion = {"Volvo","Iveco","Mercedes","Isuzu", "MAN","Scania"};
    
    private String[] accesoriosAuto = {"Sin elegir","Puertas", "Luces"};
    private String[] accesoriosMoto = {"Sin elegir","Pedales", "Espejos"};
    private String[] accesoriosCamion = {"Sin elegir","Tolva", "Ejes"};
    
    private Map<String, Integer> preciosAccesoriosAuto = Map.of(
        "Puertas", 1000,
        "Luces", 600
    );

    private Map<String, Integer> preciosAccesoriosMoto = Map.of(
        "Pedales", 1000,
        "Espejos", 8000
    );

    private Map<String, Integer> preciosAccesoriosCamion = Map.of(
        "Tolva o Caja", 10000,
        "Ejes", 8000
    );

    private Map<String, Integer> preciosMarcasAuto = Map.of(
        "Toyota", 19000,
        "Hyundai", 16000,
        "Suzuki", 12000,
        "Ford", 17000,
        "Chevrolet", 18000,
        "Honda", 21000
    );

    private Map<String, Integer> preciosMarcasMoto = Map.of(
        "Yamaha", 14000,
        "Suzuki", 8000,
        "Honda", 15000,
        "KTM", 5000,
        "BMW", 18000,
        "Kawasaki", 13000
    );

    private Map<String, Integer> preciosMarcasCamion = Map.of(
        "Volvo", 100000,
        "Iveco", 85000,
        "Mercedes", 110000,
        "Isuzu", 70000,
        "MAN", 105000,
        "Scania", 95000
    );
    private int currentRow = -1;
    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        grupoBotones = new javax.swing.ButtonGroup();
        grupobotones_remoto = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        text_name = new javax.swing.JTextField();
        text_rut = new javax.swing.JTextField();
        guardar = new javax.swing.JButton();
        boton_vehiculo = new javax.swing.JRadioButton();
        boton_accesorios = new javax.swing.JRadioButton();
        tipo_vehiculo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        tipo_accesorios = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        tipo_marca = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        text_cantidad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        text_año = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        agregar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        control_si = new javax.swing.JRadioButton();
        control_no = new javax.swing.JRadioButton();
        subtotal = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        descuento = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        boton_marca = new javax.swing.JButton();
        boton_ano = new javax.swing.JButton();
        boton_remoto = new javax.swing.JButton();
        boton_camion = new javax.swing.JButton();
        boton_auto = new javax.swing.JButton();
        boton_moto = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        vental_total = new javax.swing.JTextField();
        ventas_hoy = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 102, 255));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setToolTipText("");

        jLabel1.setText("NOMBRE");

        jLabel2.setText("RUT");

        text_name.setName("text_name"); // NOI18N
        text_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_nameActionPerformed(evt);
            }
        });

        text_rut.setName("text_rut"); // NOI18N
        text_rut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_rutActionPerformed(evt);
            }
        });

        guardar.setText("Guardar");
        guardar.setName("guardar"); // NOI18N
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        grupoBotones.add(boton_vehiculo);
        boton_vehiculo.setText("VEHICULO");
        boton_vehiculo.setName("boton_vehiculo"); // NOI18N
        boton_vehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_vehiculoActionPerformed(evt);
            }
        });

        grupoBotones.add(boton_accesorios);
        boton_accesorios.setText("ACCESORIOS");
        boton_accesorios.setName("boton_accesorios"); // NOI18N
        boton_accesorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_accesoriosActionPerformed(evt);
            }
        });

        tipo_vehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar","auto", "moto", "camion" }));
        tipo_vehiculo.setName("tipo_vehiculo"); // NOI18N
        tipo_vehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo_vehiculoActionPerformed(evt);
            }
        });

        jLabel3.setText("VEHICULO");

        tipo_accesorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo_accesoriosActionPerformed(evt);
            }
        });

        jLabel4.setText("ACCESORIOS");

        tipo_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo_marcaActionPerformed(evt);
            }
        });

        jLabel5.setText("MARCA");

        jLabel6.setText("CANTIDAD");

        text_cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_cantidadActionPerformed(evt);
            }
        });

        jLabel7.setText("AÑO");

        text_año.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_añoActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/herenciap/img.jpeg"))); // NOI18N

        agregar.setText("AGREGAR");
        agregar.setName("salir"); // NOI18N
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        jLabel12.setText("CONTROL REMOTO");

        grupobotones_remoto.add(control_si);
        control_si.setText("SI");
        control_si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                control_siActionPerformed(evt);
            }
        });

        grupobotones_remoto.add(control_no);
        control_no.setText("NO");
        control_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                control_noActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(text_name, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(text_rut)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boton_vehiculo)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(boton_accesorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tipo_marca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tipo_accesorios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tipo_vehiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(text_cantidad)
                            .addComponent(text_año)))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(control_si)
                                .addGap(18, 18, 18)
                                .addComponent(control_no))
                            .addComponent(jLabel12))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(agregar)
                                .addGap(18, 18, 18)
                                .addComponent(guardar)
                                .addGap(13, 13, 13))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(text_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(text_rut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boton_vehiculo)
                            .addComponent(boton_accesorios))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tipo_vehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tipo_accesorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipo_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(text_año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(control_si)
                            .addComponent(control_no))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agregar)
                            .addComponent(guardar))
                        .addGap(4, 4, 4)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        subtotal.setEditable(false);

        total.setEditable(false);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "VEHICULO", "MARCA", "ACC 1", "CANT", "ACC 2", "CANT", "CONTROL", "AÑO", "PRECIO", "CANTIDAD", "IMPORTE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        jLabel13.setText("SUBTOTAL");

        descuento.setEditable(false);

        jLabel14.setText("DESCUENTO");

        jLabel15.setText("TOTAL");

        jPanel3.setBackground(new java.awt.Color(0, 204, 153));

        jLabel8.setText("REPORTES");

        boton_marca.setText("MARCA");
        boton_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_marcaActionPerformed(evt);
            }
        });

        boton_ano.setText("AÑO");

        boton_remoto.setText("CONTROL REMOTO");
        boton_remoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_remotoActionPerformed(evt);
            }
        });

        boton_camion.setText("CAMION");
        boton_camion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_camionActionPerformed(evt);
            }
        });

        boton_auto.setText("AUTO");
        boton_auto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_autoActionPerformed(evt);
            }
        });

        boton_moto.setText("MOTO");
        boton_moto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_motoActionPerformed(evt);
            }
        });

        jLabel10.setText("CANTIDAD DE VEHICULOS VENDIDOS AL DIA");

        jLabel11.setText("VENTAS TOTALES");

        vental_total.setEditable(false);
        vental_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vental_totalActionPerformed(evt);
            }
        });

        ventas_hoy.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(boton_ano)
                                    .addComponent(boton_remoto)
                                    .addComponent(boton_marca))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(boton_auto)
                                    .addComponent(boton_camion)
                                    .addComponent(boton_moto))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ventas_hoy, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(vental_total, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(104, 104, 104))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_marca)
                    .addComponent(boton_camion))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_ano)
                    .addComponent(boton_auto))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_remoto)
                    .addComponent(boton_moto))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ventas_hoy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(vental_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descuento, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(descuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_camionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_camionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_camionActionPerformed

    private void boton_motoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_motoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_motoActionPerformed

    private void boton_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_marcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_marcaActionPerformed

    private void text_añoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_añoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_añoActionPerformed

    private void text_cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_cantidadActionPerformed

    private void boton_vehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_vehiculoActionPerformed
        // TODO add your handling code here:
        control_si.setEnabled(true);
        control_no.setEnabled(true);
        tipo_vehiculo.setEnabled(true);
        tipo_accesorios.setEnabled(false);
        text_año.setEnabled(true);
    }//GEN-LAST:event_boton_vehiculoActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
        String vehiculo = (String) tipo_vehiculo.getSelectedItem();
        String marca = (String) tipo_marca.getSelectedItem();
        String accesorio = (String) tipo_accesorios.getSelectedItem();
        String control = control_si.isSelected() ? "SI" : "NO";
        String anio = text_año.getText();
        String cantidadStr = text_cantidad.getText();

        if (boton_vehiculo.isSelected()) {
            // Validar que vehículo, año y cantidad estén llenos y sean numéricos
            if (vehiculo.equals("Seleccionar") || marca.equals("Item 1") || anio.isEmpty() || cantidadStr.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Por favor complete todos los campos requeridos.");
                return;
            }
            if (!anio.matches("\\d+") || !cantidadStr.matches("\\d+")) {
                javax.swing.JOptionPane.showMessageDialog(this, "El año y la cantidad deben ser números.");
                return;
            }
        } else if (boton_accesorios.isSelected()) {
            // Validar que la cantidad esté llena y sea numérica
            if (cantidadStr.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Por favor ingrese la cantidad.");
                return;
            }
            if (!cantidadStr.matches("\\d+")) {
                javax.swing.JOptionPane.showMessageDialog(this, "La cantidad debe ser un número.");
                return;
            }
        }

        int cantidad = Integer.parseInt(cantidadStr);
        int precioAccesorio = 0;
        int precioMarca = 0;

        switch (vehiculo.toLowerCase()) {
            case "auto":
                precioMarca = preciosMarcasAuto.getOrDefault(marca, 0);
                precioAccesorio = preciosAccesoriosAuto.getOrDefault(accesorio, 0);
                break;
            case "moto":
                precioMarca = preciosMarcasMoto.getOrDefault(marca, 0);
                precioAccesorio = preciosAccesoriosMoto.getOrDefault(accesorio, 0);
                break;
            case "camion":
                precioMarca = preciosMarcasCamion.getOrDefault(marca, 0);
                precioAccesorio = preciosAccesoriosCamion.getOrDefault(accesorio, 0);
                break;
        }

        DefaultTableModel model = (DefaultTableModel) tabla.getModel();

        if (boton_vehiculo.isSelected()) {
            currentRow = model.getRowCount();
            model.addRow(new Object[]{vehiculo, marca, "-", 0, "-", 0, control, anio, precioMarca, cantidad, precioMarca * cantidad});
        } else if (boton_accesorios.isSelected()) {
            boolean found = false;
            for (int i = 0; i < model.getRowCount(); i++) {
                if (model.getValueAt(i, 0).equals(vehiculo) && model.getValueAt(i, 1).equals(marca)) {
                    found = true;
                    currentRow = i;
                    break;
                }
            }

            if (!found) {
                javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar un vehículo existente para agregar accesorios.");
                return; // Salir del método si no se encuentra un vehículo correspondiente
            }

            String acc1 = (String) model.getValueAt(currentRow, 2);
            int cant1 = (int) model.getValueAt(currentRow, 3);
            String acc2 = (String) model.getValueAt(currentRow, 4);
            int cant2 = (int) model.getValueAt(currentRow, 5);

            if (esAccesorio1(accesorio)) {
                if (acc1.equals("-") || acc1.equals(accesorio)) {
                    model.setValueAt(accesorio, currentRow, 2);
                    model.setValueAt(cant1 + cantidad, currentRow, 3);
                } else if (!acc1.equals(accesorio) && acc2.equals("-")) {
                    model.setValueAt(accesorio, currentRow, 4);
                    model.setValueAt(cantidad, currentRow, 5);
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Ya existen dos accesorios diferentes para este vehículo.");
                    return;
                }
            } else if (esAccesorio2(accesorio)) {
                if (acc2.equals("-") || acc2.equals(accesorio)) {
                    model.setValueAt(accesorio, currentRow, 4);
                    model.setValueAt(cant2 + cantidad, currentRow, 5);
                } else if (!acc2.equals(accesorio) && acc1.equals("-")) {
                    model.setValueAt(accesorio, currentRow, 2);
                    model.setValueAt(cantidad, currentRow, 3);
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Ya existen dos accesorios diferentes para este vehículo.");
                    return;
                }
            }

            int precioTotal = (int) model.getValueAt(currentRow, 8) + precioAccesorio * cantidad;
            model.setValueAt(precioTotal, currentRow, 8);
            int cantidadTotal = (int) model.getValueAt(currentRow, 9) + cantidad;
            model.setValueAt(cantidadTotal, currentRow, 9);
            model.setValueAt(precioTotal * cantidadTotal, currentRow, 10);

            currentRow = -1;  // Reset current row after adding accessories
        }

        // Limpiar los campos de texto
        if (tipo_accesorios.getItemCount() > 0) {
            tipo_accesorios.setSelectedIndex(0);
        }
        control_si.setSelected(false);
        control_no.setSelected(false);
        text_año.setText("");
        text_cantidad.setText("");
    }//GEN-LAST:event_agregarActionPerformed

private boolean esAccesorio1(String accesorio) {
    return accesorio.equals("Puertas") || accesorio.equals("Pedales") || accesorio.equals("Tolva");
}

private boolean esAccesorio2(String accesorio) {
    return accesorio.equals("Luces") || accesorio.equals("Espejos") || accesorio.equals("Ejes");
}
    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarActionPerformed

    private void text_rutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_rutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_rutActionPerformed

    private void text_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_nameActionPerformed

    private void boton_remotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_remotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_remotoActionPerformed

    private void vental_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vental_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vental_totalActionPerformed

    private void boton_autoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_autoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_autoActionPerformed

    private void control_siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_control_siActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_control_siActionPerformed

    private void control_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_control_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_control_noActionPerformed

    private void boton_accesoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_accesoriosActionPerformed
        // TODO add your handling code here:
         control_si.setEnabled(false);
        control_no.setEnabled(false);
        tipo_vehiculo.setEnabled(false);
        tipo_accesorios.setEnabled(true);
        text_año.setEnabled(false);
    }//GEN-LAST:event_boton_accesoriosActionPerformed

    private void tipo_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo_marcaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tipo_marcaActionPerformed

    private void tipo_vehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo_vehiculoActionPerformed
        // TODO add your handling code here:
        String tipo = (String) tipo_vehiculo.getSelectedItem();
        
        switch (tipo.toLowerCase()) {
            case "auto":
                tipo_marca.setModel(new javax.swing.DefaultComboBoxModel<>(marcasAuto));
                tipo_accesorios.setModel(new javax.swing.DefaultComboBoxModel<>(accesoriosAuto));
                break;
            case "moto":
                tipo_marca.setModel(new javax.swing.DefaultComboBoxModel<>(marcasMoto));
                tipo_accesorios.setModel(new javax.swing.DefaultComboBoxModel<>(accesoriosMoto));
                break;
            case "camion":
                tipo_marca.setModel(new javax.swing.DefaultComboBoxModel<>(marcasCamion));
                tipo_accesorios.setModel(new javax.swing.DefaultComboBoxModel<>(accesoriosCamion));
                break;
            default:
                tipo_marca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{}));
                tipo_accesorios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{}));
                break;
        }
    }//GEN-LAST:event_tipo_vehiculoActionPerformed

    private void tipo_accesoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo_accesoriosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipo_accesoriosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JRadioButton boton_accesorios;
    private javax.swing.JButton boton_ano;
    private javax.swing.JButton boton_auto;
    private javax.swing.JButton boton_camion;
    private javax.swing.JButton boton_marca;
    private javax.swing.JButton boton_moto;
    private javax.swing.JButton boton_remoto;
    private javax.swing.JRadioButton boton_vehiculo;
    private javax.swing.JRadioButton control_no;
    private javax.swing.JRadioButton control_si;
    private javax.swing.JTextField descuento;
    private javax.swing.ButtonGroup grupoBotones;
    private javax.swing.ButtonGroup grupobotones_remoto;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField subtotal;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField text_año;
    private javax.swing.JTextField text_cantidad;
    private javax.swing.JTextField text_name;
    private javax.swing.JTextField text_rut;
    private javax.swing.JComboBox<String> tipo_accesorios;
    private javax.swing.JComboBox<String> tipo_marca;
    private javax.swing.JComboBox<String> tipo_vehiculo;
    private javax.swing.JTextField total;
    private javax.swing.JTextField vental_total;
    private javax.swing.JTextField ventas_hoy;
    // End of variables declaration//GEN-END:variables
}
